export const GET_MASTER_DATA_REQUEST = 'GET_MASTER_DATA_REQUEST';
export const GET_MASTER_DATA_SUCCESS = 'GET_MASTER_DATA_SUCCESS';
export const GET_MASTER_DATA_FAILURE = 'GET_MASTER_DATA_FAILURE';

export const ADD_MASTER_TO_FAVORITES_REQUEST = 'ADD_MASTER_TO_FAVORITES_REQUEST';
export const ADD_MASTER_TO_FAVORITES_SUCCESS = 'ADD_MASTER_TO_FAVORITES_SUCCESS';
export const ADD_MASTER_TO_FAVORITES_FAILURE = 'ADD_MASTER_TO_FAVORITES_FAILURE';

export const REMOVE_MASTER_FROM_FAVORITES_REQUEST = 'REMOVE_MASTER_FROM_FAVORITES_REQUEST';
export const REMOVE_MASTER_FROM_FAVORITES_SUCCESS = 'REMOVE_MASTER_FROM_FAVORITES_SUCCESS';
export const REMOVE_MASTER_FROM_FAVORITES_FAILURE = 'REMOVE_MASTER_FROM_FAVORITES_FAILURE';

export const TOGGLE_LIKE = 'TOGGLE_LIKE';

export const DELETE_PHOTO = 'DELETE_PHOTO';

export const GET_MASTER_FEEDBACKS_REQUEST = 'GET_MASTER_FEEDBACKS_REQUEST';
export const GET_MASTER_FEEDBACKS_SUCCESS = 'GET_MASTER_FEEDBACKS_SUCCESS';
export const GET_MASTER_FEEDBACKS_FAILURE = 'GET_MASTER_FEEDBACKS_FAILURE';

export const GIVE_MASTER_FEEDBACK_REQUEST = 'GIVE_MASTER_FEEDBACK_REQUEST';
export const GIVE_MASTER_FEEDBACK_SUCCESS = 'GIVE_MASTER_FEEDBACK_SUCCESS';
export const GIVE_MASTER_FEEDBACK_FAILURE = 'GIVE_MASTER_FEEDBACK_FAILURE';
