export const GET_STUDIO_DATA_REQUEST = 'GET_STUDIO_DATA_REQUEST';
export const GET_STUDIO_DATA_SUCCESS = 'GET_STUDIO_DATA_SUCCESS';
export const GET_STUDIO_DATA_FAILURE = 'GET_STUDIO_DATA_FAILURE';

export const GET_MASTERS_REQUEST = 'GET_MASTERS_REQUEST';
export const GET_MASTERS_SUCCESS = 'GET_MASTERS_SUCCESS';
export const GET_MASTERS_FAILURE = 'GET_MASTERS_FAILURE';

export const REGISTER_MASTERS_REQUEST = 'REGISTER_MASTERS_REQUEST';
export const REGISTER_MASTERS_SUCCESS = 'REGISTER_MASTERS_SUCCESS';
export const REGISTER_MASTERS_FAILURE = 'REGISTER_MASTERS_FAILURE';

export const ADD_STUDIO_TO_FAVORITES_REQUEST = 'ADD_STUDIO_TO_FAVORITES_REQUEST';
export const ADD_STUDIO_TO_FAVORITES_SUCCESS = 'ADD_STUDIO_TO_FAVORITES_SUCCESS';
export const ADD_STUDIO_TO_FAVORITES_FAILURE = 'ADD_STUDIO_TO_FAVORITES_FAILURE';

export const REMOVE_STUDIO_FROM_FAVORITES_REQUEST = 'REMOVE_STUDIO_FROM_FAVORITES_REQUEST';
export const REMOVE_STUDIO_FROM_FAVORITES_SUCCESS = 'REMOVE_STUDIO_FROM_FAVORITES_SUCCESS';
export const REMOVE_STUDIO_FROM_FAVORITES_FAILURE = 'REMOVE_STUDIO_FROM_FAVORITES_FAILURE';

export const GET_STUDIO_FEEDBACKS_REQUEST = 'GET_STUDIO_FEEDBACKS_REQUEST';
export const GET_STUDIO_FEEDBACKS_SUCCESS = 'GET_STUDIO_FEEDBACKS_SUCCESS';
export const GET_STUDIO_FEEDBACKS_FAILURE = 'GET_STUDIO_FEEDBACKS_FAILURE';

export const GIVE_STUDIO_FEEDBACK_REQUEST = 'GIVE_STUDIO_FEEDBACK_REQUEST';
export const GIVE_STUDIO_FEEDBACK_SUCCESS = 'GIVE_STUDIO_FEEDBACK_SUCCESS';
export const GIVE_STUDIO_FEEDBACK_FAILURE = 'GIVE_STUDIO_FEEDBACK_FAILURE';
