export const GET_STUDIO_DATA_REQUEST = 'GET_STUDIO_DATA_REQUEST';
export const GET_STUDIO_DATA_SUCCESS = 'GET_STUDIO_DATA_SUCCESS';
export const GET_STUDIO_DATA_FAILURE = 'GET_STUDIO_DATA_FAILURE';

export const GET_MASTERS_REQUEST = 'GET_MASTERS_REQUEST';
export const GET_MASTERS_SUCCESS = 'GET_MASTERS_SUCCESS';
export const GET_MASTERS_FAILURE = 'GET_MASTERS_FAILURE';

export const REGISTER_MASTERS_REQUEST = 'REGISTER_MASTERS_REQUEST';
export const REGISTER_MASTERS_SUCCESS = 'REGISTER_MASTERS_SUCCESS';
export const REGISTER_MASTERS_FAILURE = 'REGISTER_MASTERS_FAILURE';
