export const GET_USERS_LIST_REQUEST = 'GET_USERS_LIST_REQUEST';
export const GET_USERS_LIST_SUCCESS = 'GET_USERS_LIST_SUCCESS';
export const GET_USERS_LIST_FAILURE = 'GET_USERS_LIST_FAILURE';

export const BAN_USER_REQUEST = 'BAN_USER_REQUEST';
export const BAN_USER_SUCCESS = 'BAN_USER_SUCCESS';
export const BAN_USER_FAILURE = 'BAN_USER_FAILURE';

export const UNBAN_USER_REQUEST = 'UNBAN_USER_REQUEST';
export const UNBAN_USER_SUCCESS = 'UNBAN_USER_SUCCESS';
export const UNBAN_USER_FAILURE = 'UNBAN_USER_FAILURE';
