export const GET_PHOTOS_REQUEST = 'GET_PHOTOS_REQUEST';
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const GET_PHOTOS_FAILURE = 'GET_PHOTOS_FAILURE';

export const TOGGLE_LIKE = 'TOGGLE_LIKE';

export const DELETE_PHOTO = 'DELETE_PHOTO';

export const CLEAR_PHOTOS = 'CLEAR_PHOTOS';
