export const UPLOAD_PHOTO_REQUEST = 'UPLOAD_PHOTO_REQUEST';
export const UPLOAD_PHOTO_SUCCESS = 'UPLOAD_PHOTO_SUCCESS';
export const UPLOAD_PHOTO_FAILURE = 'UPLOAD_PHOTO_FAILURE';

export const REGISTER_STUDIO_REQUEST = 'REGISTER_STUDIO_REQUEST';
export const REGISTER_STUDIO_SUCCESS = 'REGISTER_STUDIO_SUCCESS';
export const REGISTER_STUDIO_FAILURE = 'REGISTER_STUDIO_FAILURE';

export const RESET_ERROR = 'RESET_ERROR';

export const GET_PHOTOS_REQUEST = 'GET_PHOTOS_REQUEST';
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const GET_PHOTOS_FAILURE = 'GET_PHOTOS_FAILURE';

export const DELETE_PHOTO = 'DELETE_PHOTO';

export const CLEAR_PHOTOS = 'CLEAR_PHOTOS';

export const TOGGLE_LIKE = 'TOGGLE_LIKE';

export const GET_FAVORITE_STUDIOS_REQUEST = 'GET_FAVORITE_STUDIOS_REQUEST';
export const GET_FAVORITE_STUDIOS_SUCCESS = 'GET_FAVORITE_STUDIOS_SUCCESS';
export const GET_FAVORITE_STUDIOS_FAILURE = 'GET_FAVORITE_STUDIOS_FAILURE';

export const REMOVE_STUDIO_FROM_FAVORITES_REQUEST = 'REMOVE_STUDIO_FROM_FAVORITES_REQUEST';
export const REMOVE_STUDIO_FROM_FAVORITES_SUCCESS = 'REMOVE_STUDIO_FROM_FAVORITES_SUCCESS';
export const REMOVE_STUDIO_FROM_FAVORITES_FAILURE = 'REMOVE_STUDIO_FROM_FAVORITES_FAILURE';
