export const UPLOAD_PHOTO_REQUEST = 'UPLOAD_PHOTO_REQUEST';
export const UPLOAD_PHOTO_SUCCESS = 'UPLOAD_PHOTO_SUCCESS';
export const UPLOAD_PHOTO_FAILURE = 'UPLOAD_PHOTO_FAILURE';

export const REGISTER_STUDIO_REQUEST = 'REGISTER_STUDIO_REQUEST';
export const REGISTER_STUDIO_SUCCESS = 'REGISTER_STUDIO_SUCCESS';
export const REGISTER_STUDIO_FAILURE = 'REGISTER_STUDIO_FAILURE';

export const RESET_ERROR = 'RESET_ERROR';
