export const GET_STUDIOS_REQUEST = 'GET_STUDIOS_REQUEST';
export const GET_STUDIOS_SUCCESS = 'GET_STUDIOS_SUCCESS';
export const GET_STUDIOS_FAILURE = 'GET_STUDIOS_FAILURE';

export const REGISTER_STUDIO_REQUEST = 'REGISTER_STUDIO_REQUEST';
export const REGISTER_STUDIO_SUCCESS = 'REGISTER_STUDIO_SUCCESS';
export const REGISTER_STUDIO_FAILURE = 'REGISTER_STUDIO_FAILURE';
