export const photoGridConstants = {
    SET_COLUMNS: 'SET_COLUMNS',
    SET_MODAL_PHOTO: 'SET_MODAL_PHOTO',
    SET_MODAL_OPEN_FLAG: 'SET_MODAL_OPEN_FLAG',

    TOGGLE_MODAL_PHOTO_LIKE: 'TOGGLE_MODAL_PHOTO_LIKE'
}