export const photoGridConstants = {
    SET_COLUMNS: 'SET_COLUMNS',
    SET_MODAL_PHOTO: 'SET_MODAL_PHOTO',
    SET_MODAL_OPEN_FLAG: 'SET_MODAL_OPEN_FLAG',

    TOGGLE_MODAL_PHOTO_LIKE: 'TOGGLE_MODAL_PHOTO_LIKE',

    DELETE_PHOTO_REQUEST: 'DELETE_PHOTO_REQUEST',
    DELETE_PHOTO_SUCCESS: 'DELETE_PHOTO_SUCCESS',
    DELETE_PHOTO_FAILURE: 'DELETE_PHOTO_FAILURE',

    LIKE_PHOTO_REQUEST: 'LIKE_PHOTO_REQUEST',
    LIKE_PHOTO_SUCCESS: 'LIKE_PHOTO_SUCCESS',
    LIKE_PHOTO_FAILURE: 'LIKE_PHOTO_FAILURE',

    TOGGLE_LIKE: 'TOGGLE_LIKE',

    GET_COMMENTS_REQUEST: 'GET_COMMENTS_REQUEST',
    GET_COMMENTS_SUCCESS: 'GET_COMMENTS_SUCCESS',
    GET_COMMENTS_FAILURE: 'GET_COMMENTS_FAILURE',

    ADD_COMMENT_REQUEST: 'ADD_COMMENT_REQUEST',
    ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
    ADD_COMMENT_FAILURE: 'ADD_COMMENT_FAILURE',

};
